name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10.8' 
       
    - shell: cmd
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - shell: cmd
      run: |
        md Downloads &&^
        python fetch_vcdist.py --destination=%cd% --include-old-versions

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: vcredist*
        filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
